application:
  runtimeManifest:
    packages:
      main:
        license: Apache-2.0
        actions:
          convert:
            function: dist/main.cjs
            web: 'yes'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false # explicitly unauthenticated action
              final: true